version: '3.8'

services:
  web:
    command: python3 -m flask run -h 0.0.0.0 -p 8000 --debugger --reload
    env_file: .env
    build:
      context: .
    volumes:
    - .:/usr/src/app/
    ports:
    - "8000:8000"
